[project]
name = 'Decentralized-Cosmic-Evolutionary-Guidance-Systems'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.civilization-advancement-milestone]
path = 'contracts/civilization-advancement-milestone.clar'
clarity_version = 2
epoch = 2.5

[contracts.evolutionary-bottleneck-prevention]
path = 'contracts/evolutionary-bottleneck-prevention.clar'
clarity_version = 2
epoch = 2.5

[contracts.galactic-biodiversity-preservation]
path = 'contracts/galactic-biodiversity-preservation.clar'
clarity_version = 2
epoch = 2.5

[contracts.species-development-trajectory]
path = 'contracts/species-development-trajectory.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
